language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm
sudo: false
install:
    - git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure && make && make install && cd ../
    - git clone https://github.com/arnaud-lb/php-rdkafka.git cd php-rdkafka/ && phpize && ./configure && make && make install && cd ../
    - echo "extension = rdkafka.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - apt install libzookeeper2 -q
    - git clone https://github.com/andreiz/php-zookeeper.git && cd php-zookeeper && phpize && ./configure && make && make install && cd ../
    - echo "extension = zookeeper.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: make travis
matrix:
    fast_finish: true
    allow_failures:
        - php: 5.4
        - php: hhvm
        - php: nightly
after_script:
    - php vendor/bin/coveralls
