language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm
sudo: false
script: make travis
matrix:
    fast_finish: true
    allow_failures:
        - php: 5.4
        - php: hhvm
        - php: nightly
after_script:
    - php vendor/bin/coveralls
